// Game registry — metadata the hub uses to render cards and launch games.
// Covers are generated from CSS gradients + emoji, so no image assets are needed.
// `path` is relative to the hub root (index.html), launched via full-page navigation.
export const GAMES = [
  {
    id: 'tactical-strike',
    title: 'TACTICAL STRIKE',
    subtitle: '3D 战术射击 · FPS',
    desc: '第一人称射击 · WASD 移动 · 鼠标瞄准 · 购买武器 · Three.js 引擎',
    icon: '🔫',
    accent: '#ff5a3c',
    accent2: '#7a1505',
    tags: ['单人', 'FPS', '键鼠'],
    path: 'games/tactical-strike/index.html',
  },
  {
    id: 'snake',
    title: '蛇蛇王国 SNAKE',
    subtitle: '多人吞噬竞技',
    desc: '摇杆操控 · 吞噬成长 · 技能冲刺 · 子弹击败对手 · Canvas 2D',
    icon: '🐍',
    accent: '#3cd070',
    accent2: '#0a5e2e',
    tags: ['竞技', '休闲', '触屏/鼠标'],
    path: 'games/snake/dist/index.html',
  },
  {
    id: 'breakout',
    title: '打砖块 BREAKOUT',
    subtitle: '糖果消砖 · 益智休闲',
    desc: '挡板接球 · 击碎糖果砖块 · 掉落道具 · 主题关卡 · 键鼠/手柄',
    icon: '🧱',
    accent: '#ff6fae',
    accent2: '#b3306e',
    tags: ['休闲', '益智', '键鼠/手柄'],
    path: 'games/breakout/index.html',
  },
  {
    id: 'jungle-blitz',
    title: '丛林尖兵 JUNGLE BLITZ',
    subtitle: '横版跑射 · 闯关打 BOSS',
    desc: '跑跳射击 · 八方向瞄准 · 武器升级 · 5 关 5 BOSS · 键盘/手柄',
    icon: '🪖',
    accent: '#8bc34a',
    accent2: '#33501a',
    tags: ['闯关', '动作', '键盘/手柄'],
    path: 'games/jungle-blitz/index.html',
  },
  {
    id: 'pixel-quest',
    title: '像素冒险 PIXEL QUEST',
    subtitle: '横版闯关 · 拯救公主',
    desc: '跑跳踩怪 · 蘑菇变大 · 火球星星 · 4 关救公主 · 键鼠/手柄',
    icon: '🍄',
    accent: '#e8362b',
    accent2: '#9c1f17',
    tags: ['冒险', '跳跃', '键鼠/手柄'],
    path: 'games/pixel-quest/index.html',
  },
  {
    id: 'turbo-drift',
    title: '极速飞车 TURBO DRIFT',
    subtitle: '伪3D 漂移竞速 · 从下往上开',
    desc: '伪3D 第三人称竞速 · 漂移攒氮气 · 道具战 · 4 赛道 4 车 · 键鼠/手柄',
    icon: '🏎️',
    accent: '#5161ff',
    accent2: '#1a2270',
    tags: ['竞速', '漂移', '键鼠/手柄'],
    path: 'games/turbo-drift/index.html',
  },
  {
    id: 'caocao-zhuan',
    title: '群雄逐鹿·孟德篇',
    subtitle: '三国战棋 · 回合制 SRPG',
    desc: '等距3D战棋 · 兵种相克 · 计略单挑 · 剧情演出 · 键鼠',
    icon: '⚔️',
    accent: '#d4af37',
    accent2: '#7a1f1f',
    tags: ['策略', '战棋', '三国', '键鼠'],
    path: 'games/caocao-zhuan/index.html',
  },
  {
    id: 'boom-worms',
    title: '炮炮虫 BOOM WORMS',
    subtitle: '回合制炮战 · 打飞小虫',
    desc: '回合制策略 · 抛物线瞄准 · 可破坏地形 · 单人闯关/双人同机 · 键鼠/手柄',
    icon: '🪱',
    accent: '#ff9f43',
    accent2: '#b3590a',
    tags: ['策略', '回合制', '键鼠/手柄'],
    path: 'games/boom-worms/index.html',
  },
  {
    id: 'tower-defender',
    title: '成都保卫战',
    subtitle: '三国塔防 · 守城御敌',
    desc: '实时波次塔防 · 蜀汉六将布防 · 升级招牌技 · 三势力 8 关战役 · 名将 BOSS · 键鼠/触屏',
    icon: '🏯',
    accent: '#e8a020',
    accent2: '#4d3a24',
    tags: ['塔防', '策略', '三国', '键鼠/触屏'],
    path: 'games/tower-defender/index.html',
  },
  {
    id: 'bomb-zombie',
    title: '向僵尸开炮 BOMB ZOMBIE',
    subtitle: '阵地防守 · 自动射击 · roguelite 构筑',
    desc: '底部炮台守城墙 · 僵尸潮割草 · 升级三选一滚雪球 · 进化卡质变 · 主动技能 · 触屏/键鼠',
    icon: '🧟',
    accent: '#7cff5a',
    accent2: '#2a7a1a',
    tags: ['割草', 'Roguelite', '构筑'],
    path: 'games/bomb-zombie/index.html',
  },
];
